/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'article-body': ['Poppins', 'sans-serif'],
        'display-lg': ['Poppins', 'sans-serif'],
        'headline-xl-mobile': ['Poppins', 'sans-serif'],
        'headline-xl': ['Poppins', 'sans-serif'],
        'body-md': ['Poppins', 'sans-serif'],
        'label-sm': ['Poppins', 'sans-serif'],
        'caption': ['Poppins', 'sans-serif']
      },
      fontSize: {
        'article-body': ['18px', { lineHeight: '32px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'caption': ['14px', { lineHeight: '20px', fontWeight: '500' }]
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '3xl': '1.5rem'
      },
      spacing: {
        'header-height': '72px',
        'container-max': '1280px',
        gutter: '24px',
        'stack-gap': '32px',
        'margin-mobile': '16px'
      },
      colors: {
        'inverse-primary': '#93ccff',
        'on-primary-fixed': '#001d31',
        'on-primary-container': '#fdfcff',
        'primary-fixed': '#cce5ff',
        'on-tertiary-fixed-variant': '#005236',
        'on-secondary-container': '#004666',
        'status-error': '#EF4444',
        'on-primary-fixed-variant': '#004b73',
        outline: '#707881',
        'on-tertiary-fixed': '#002113',
        'on-error': '#ffffff',
        secondary: '#006591',
        surface: '#f8f9ff',
        'secondary-container': '#39b8fd',
        'outline-variant': '#bfc7d2',
        'secondary-fixed': '#c9e6ff',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'on-background': '#0b1c30',
        'surface-bright': '#f8f9ff',
        'on-surface': '#0b1c30',
        'on-primary': '#ffffff',
        'brand-bg-light': '#F0FDF8',
        'surface-container-highest': '#d3e4fe',
        'primary-container': '#007bb9',
        'on-surface-variant': '#3f4850',
        'on-secondary-fixed': '#001e2f',
        'inverse-on-surface': '#eaf1ff',
        background: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'surface-tint': '#006398',
        'surface-variant': '#d3e4fe',
        'on-secondary': '#ffffff',
        'surface-container': '#e5eeff',
        'accent-lime': '#84CC16',
        'tertiary-fixed': '#6ffbbe',
        'on-secondary-fixed-variant': '#004c6e',
        'primary-fixed-dim': '#93ccff',
        'surface-container-low': '#eff4ff',
        'surface-slate-900': '#0F172A',
        'tertiary-container': '#00855b',
        error: '#ba1a1a',
        'surface-dim': '#cbdbf5',
        tertiary: '#006947',
        'on-tertiary-container': '#f5fff6',
        primary: '#006194',
        'secondary-fixed-dim': '#89ceff',
        'inverse-surface': '#213145',
        'surface-container-high': '#dce9ff',
        'tertiary-fixed-dim': '#4edea3',
        brand: {
          50: 'rgb(var(--color-brand-50) / <alpha-value>)',
          100: 'rgb(var(--color-brand-100) / <alpha-value>)',
          200: 'rgb(var(--color-brand-200) / <alpha-value>)',
          300: 'rgb(var(--color-brand-300) / <alpha-value>)',
          400: 'rgb(var(--color-brand-400) / <alpha-value>)',
          500: 'rgb(var(--color-brand-500) / <alpha-value>)',
          600: 'rgb(var(--color-brand-600) / <alpha-value>)',
          700: 'rgb(var(--color-brand-700) / <alpha-value>)',
          800: 'rgb(var(--color-brand-800) / <alpha-value>)',
          900: 'rgb(var(--color-brand-900) / <alpha-value>)'
        }
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
